package org.example.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Date;
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Project {
    private Integer id;
    private String name;
    private String slug;
    private String description;
    private Date created_date;
    private Date modified_date;
    private Owner owner;
    private ArrayList<Member> members;
    private Object total_milestones;
    private Object total_story_poIntegers;
    private Boolean is_contact_activated;
    private Boolean is_epics_activated;
    private Boolean is_backlog_activated;
    private Boolean is_kanban_activated;
    private Boolean is_wiki_activated;
    private Boolean is_issues_activated;
    private Object videoconferences;
    private Object videoconferences_extra_data;
    private Integer creation_template;
    private Boolean is_private;
    private ArrayList<String> anon_permissions;
    private ArrayList<String> public_permissions;
    private Boolean is_featured;
    private Boolean is_looking_for_people;
    private String looking_for_people_note;
    private Object blocked_code;
    private Date totals_updated_datetime;
    private int total_fans;
    private int total_fans_last_week;
    private int total_fans_last_month;
    private int total_fans_last_year;
    private int total_activity;
    private int total_activity_last_week;
    private int total_activity_last_month;
    private int total_activity_last_year;
    private ArrayList<Object> tags;
    private TagsColors tags_colors;
    private Integer default_epic_status;
    private Integer default_poIntegers;
    private Integer default_us_status;
    private Integer default_task_status;
    private Integer default_priority;
    private Integer default_severity;
    private Integer default_issue_status;
    private Integer default_issue_type;
    private Object default_swimlane;
    private ArrayList<String> my_permissions;
    private Boolean i_am_owner;
    private Boolean i_am_admin;
    private Boolean i_am_member;
    private Integer notify_level;
    private Integer total_closed_milestones;
    private Boolean is_watcher;
    private Integer total_watchers;
    private Object logo_small_url;
    private Object logo_big_url;
    private Boolean is_fan;
    private Boolean my_homepage;
    private ArrayList<EpicStatus> epic_statuses;
    private Object swimlanes;
    private ArrayList<UsStatus> us_statuses;
    private ArrayList<UsDuedate> us_duedates;
    private ArrayList<Point> points;
    private ArrayList<TaskStatus> task_statuses;
    private ArrayList<TaskDuedate> task_duedates;
    private ArrayList<IssueStatus> issue_statuses;
    private ArrayList<IssueType> issue_types;
    private ArrayList<IssueDuedate> issue_duedates;
    private ArrayList<Priority> priorities;
    private ArrayList<Severity> severities;
    private Object epic_custom_attributes;
    private Object userstory_custom_attributes;
    private Object task_custom_attributes;
    private Object issue_custom_attributes;
    private ArrayList<Role> roles;
    private Integer total_memberships;
    private Boolean is_out_of_owner_limits;
    private PrivateExtraInfo is_private_extra_info;
    private Object max_memberships;
    private Object epics_csv_uuid;
    private Object userstories_csv_uuid;
    private Object tasks_csv_uuid;
    private Object issues_csv_uuid;
    private Object transfer_token;
    private ArrayList<Object> milestones;
}
